# Generated by Django 3.0.3 on 2020-10-16 13:34

import backend.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(blank=True, height_field='height_img', upload_to=backend.blog.models.upload_location, width_field='width_img'),
        ),
        migrations.AddField(
            model_name='post',
            name='height_img',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_img',
            field=models.IntegerField(default=0),
        ),
    ]
